name: Build Minimal CEF + JCEF

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Set CI environment variable
        run: echo "CI=true" >> $GITHUB_ENV

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git python3 python3-pip ninja-build clang pkg-config libasound2-dev openjdk-17-jdk curl unzip
      - name: Make script executable
        run: chmod +x scripts/compile_linux.sh
      - name: Build CEF + JCEF (Minimal)
        run: |
          ./scripts/run_linux_slim.sh amd64 Release

      - name: Upload JCEF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jcef-linux-minimal
          path: artifacts/

      

